# Generated by Django 4.2.7 on 2026-02-16 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_nepali',
            field=models.TextField(blank=True, help_text='Description in Nepali'),
        ),
    ]
