# Generated by Django 4.2.7 on 2026-02-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ceo', 'CEO'), ('md', 'Managing Director')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='leadership/')),
                ('message_english', models.TextField()),
                ('message_nepali', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Leadership Message',
                'verbose_name_plural': 'Leadership Messages',
                'ordering': ['role'],
            },
        ),
    ]
