# Generated by Django 4.2.7 on 2026-02-11 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('shareholder', 'Shareholder'), ('board_member', 'Board Member')], max_length=20)),
                ('position', models.CharField(help_text='e.g., Chairman, Director, etc.', max_length=200)),
                ('photo', models.ImageField(upload_to='team/')),
                ('bio', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['role', 'order', 'name'],
            },
        ),
    ]
